=== liyanru910102/mobile_intfc/mobile_interface_mysql/src/main/resources/json/代码云查询_schema.json
{
  "$schema": "http://json-schema.org/draft-03/schema",
  "id": "#",
  "required": true,
  "type": "array",
  "items": {
    "id": "0",
    "type": "object",
    "required": true,
    "properties": {
      "stock_type": {
        "id": "stock_type",
        "type": "string",
        "required": true
      },
      "stock_market": {
        "id": "stock_market",
        "type": "string",
        "required": true
      },
      "stock_name": {
        "id": "stock_name",
        "type": "string",
        "required": true
      },
      "stock_pinyin": {
        "id": "stock_pinyin",
        "type": "string",
        "required": true
      },
      "stock_mark": {
        "id": "stock_mark",
        "type": "string",
        "required": true
      },
      "stock_code": {
        "id": "stock_code",
        "type": "string",
        "required": true
      }
    }
  }
}

=== liyanru910102/mobile_intfc/mobile_interface_mysql/src/main/resources/json/代码云查询.json
[
	{
		"stock_code": "000001",
		"stock_mark": "R",
		"stock_market": "1",
		"stock_name": "平安银行",
		"stock_pinyin": "PAYH",
		"stock_type": "1"
	},
	{
		"stock_code": "000001",
		"stock_mark": "",
		"stock_market": "2",
		"stock_name": "上证指数",
		"stock_pinyin": "SZZS",
		"stock_type": "16"
	}
]
